[project]
name = "cpu-ram-stress"
version = "0.1.0"
description = "for load your CPU and RAM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
]
